config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :recipes do
    collection do
      post :import
    end
  end
  resources :orders
  resources :recipes
  resources :merchants
  resources :customers
  resources :sms_messages
  resources :merchant_informations
  post 'add_wallet_money' => 'merchants#add_wallet_money'
  get 'cart'=> 'pages#cart'

  put 'add_to_cart' => 'recipes#add_to_cart'

  delete 'remove_cart_item' => 'recipes#remove_cart_item'
  delete 'delete_merchant' => 'merchants#destroy'

  post 'auto_complete' => 'orders#autocomplete'

  post 'new_new_order' => 'orders#new'
  get 'new_new_order' => 'customers#new'
  get 'my_orders' => 'pages#my_orders'

  post 'availability' => "recipes#availability"
  post 'shop_open' => "pages#shop_open"
  post 'cusine' => "pages#home"

  get 'closed_shop' => "pages#closed_shop"

  post 'sms_accept' => "pages#sms_accept"

  post 'send_sms' => "pages#send_sms"

  post 'accept_sms' => "pages#accept_sms"

  post 'reject_sms' => "pages#reject_sms"

  post 'order_delivery' => "orders#order_delivery"
  
  patch 'update_discount' => "pages#update_discount"
  patch 'update_pin' => "pages#update_pin"

  patch 'recipes' => "recipes#index"
  patch 'orders' => "orders#index"
  patch 'merchants' => "merchants#index"
  post 'set_sms' => "sms_messages#set_sms"
  post 'accept_merchant_information' => "merchant_informations#accept_merchant_information"
  devise_for :users, controllers: { sessions: 'users/sessions' ,:registrations => "users/registrations" }

end

app/views/shared/_homeheader.html.erb
<div class="top_nav navbar-fixed-top" style="margin-left: 0px;">
  <div class="nav_menu">
    <nav>      
    	<%= link_to root_path, :style=>"background-color:#ededed;", data: { turbolinks: false } do %>
      <img src="/images/GR-logo-new.png" width="50px" style="padding-top:5px;margin-left:5px;">
      <%end%>
      

    
       
    </nav>
  </div>
 
</div>                        


                        
  

app/views/shared/_order.html.erb
<table id="example" class="table table-bordered">
              <thead>
                <tr>
                  <th>Serial</th>
                  <th>Order ID</th>
                
                 <th>Customer Name</th>
                  <th>Phone</th>
                  <th>Address</th>
              
                  <th>Amount</th>
                  <th>Mode of Payment</th>
                  <th>Ordered Recipes</th>
                  <th>Notes</th>
                  <th>Delivery Time</th>
                  <th>Accept</th>
                  <th>Status</th>
                  
                  
                </tr>
              </thead>


              <tbody>
              <% @orders.each do |order| %>
                <tr>
                
                <td class="text-uppercase"><%= order.id %></td>
                <td class="text-uppercase"><%= order.o_id %></td>
                  <td class="text-uppercase"><%= order.customer.name %></td>
                <td class="text-uppercase"><%= order.customer.phone %></td>
                <td class="text-uppercase"><%= order.customer_address.address %></td>
             
                <td><%= order.amount %></td>
                <td class="text-uppercase"><%= order.mode_of_payment %></td>
                <td class="text-uppercase"><% order.recipes.each do |recipe| %>
                 <%= recipe.serving %> <%= recipe.name %>
                  <% end %>
                </td>
                <%if order.notes_orders.any?%>
                <td class="text-uppercase" style="background-color:red;color:white;"><% order.notes_orders.each do |note| %>
                  <%= note.description %>
                  <% end %>
                </td>
                <%else%>
                <td></td>
                <%end%>
                <td><%= order.delivery_time %></td>
                
                <td class="smsstatus" data-id="<%= order.id %>"><% if order.sms_status == "Accepted" %>
                <a class="btn btn-default" disabled="disabled">Accepted</a>
                <%elsif order.sms_status == "Rejected" %>
                <a class="btn btn-warning" disabled="disabled">Rejected</a>
                <%else %>
                <%= link_to "Accept", accept_sms_path(order), :method => :post, :class=>"smsmessage btn btn-success", remote: true, :style=>"margin-top:5px;margin-left:5px;", data: { toggle_text: 'Decline', toggle_href: shop_open_path ,id: order.id } %>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal<%=order.id%>"  style="margin-top:5px;margin-left:5px;">Decline</button>
                <div id="myModal<%=order.id%>" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body" >
        <div class="form-inline">
            <%= form_for(@stat_second, url: reject_sms_path) do |f| %>
            <!-- start form for validation -->
            <form id="demo-form" data-parsley-validate>
            <%= hidden_field_tag 'order_id', order.id %>

              <label for="fullname">Message</label>
              <%= f.text_field :discount, autofocus: true ,:class=> "form-control", data: { turbolinks: false }%>
            
             <%= f.submit "Send",:class=>"btn btn-success submit", :style=>"margin-top:5px" %>
                  

            </form>
            <% end %>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
          
       
              
              
              
              <%end%>
          </td>
          <td><% if order.sms_status == "default" %> 
                <a class="btn btn-info">UNDER REVIEW</a>
                <% elsif order.sms_status == "Rejected" %>
                <a class="btn btn-default" disabled="disabled">Rejected</a>
               
                  <%else%>
                   <% if order.is_delivered == nil  %>
                <%= link_to "NEW ORDER", order_delivery_path(order), :method => :post, :class=>"smsmessage btn btn-success", remote: true, :style=>"margin-top:5px;margin-left:5px;", data: { toggle_text: 'ORDER IN PROGRESS', toggle_href: order_delivery_path ,id: order.id } %>
                <% elsif order.is_delivered == false %>
                <%= link_to "ORDER IN PROGRESS", order_delivery_path(order), :method => :post, :class=>"smsmessage btn btn-warning", remote: true, :style=>"margin-top:5px;margin-left:5px;", data: { toggle_text: 'DELIVERED', toggle_href: order_delivery_path ,id: order.id } %>
                <% elsif order.is_delivered == true %>
                <a class="btn btn-default">DELIVERED</a>
                  <%end%>

                  <%end%>
                </td>
               
                </tr>
                
                <% end %>
                
              </tbody>
            </table>

app/views/shared/_ordered.html.erb
<table id="datatable" class="table table-bordered">
              <thead>
                <tr>
                <th>Serial</th>
                  <th>Order ID</th>
                  
                 <th>Customer Name</th>
                 <th>Merchant Name</th>
                  <th>Phone</th>
                  <th>Address</th>
                  <th>Amount</th>
                  <th>Ordered Recipes</th>
                  <th>Notes</th>
                  <th>Delivery Time</th>
                  <th>Status</th>
                  
                  
                </tr>
              </thead>


              <tbody>
              <% @orders.each do |order| %>
                <tr>
                <td class="text-uppercase"><%= order.id %></td>
                <td class="text-uppercase"><%= order.o_id %></td>
                
                  <td class="text-uppercase"><%= order.customer.name %></td>
                  <td class="text-uppercase"><%= order.user.full_name %></td>
                <td class="text-uppercase"><%= order.customer.phone %></td>
                <td class="text-uppercase"><%= order.customer_address.address %></td>
                <td><%= order.amount %></td>
               
                <td class="text-uppercase h4"><% order.recipes.each do |recipe| %>
                 <%= recipe.serving %><span class="h5">S </span><%= recipe.name %>,
                  <% end %>
                </td>
                <%if order.notes_orders.any?%>
                <td class="text-uppercase" style="background-color:red;color:white;"><% order.notes_orders.each do |note| %>
                  <%= note.description %>
                  <% end %>
                </td>
                <%else%>
                <td></td>
                <%end%>
                <td class="h3" style="color:blue;"><%= order.delivery_time %></td>
                <td><% if order.sms_status == "default" %> 
                <a class="btn btn-info">UNDER REVIEW</a>
               
                  <%else%>
                   <% if order.is_delivered == nil  %>
                <%= link_to "NEW ORDER", order_delivery_path(order), :method => :post, :class=>"smsmessage btn btn-success", remote: true, :style=>"margin-top:5px;margin-left:5px;", data: { toggle_text: 'ORDER IN PROGRESS', toggle_href: order_delivery_path ,id: order.id } %>
                <% elsif order.is_delivered == false %>
                <%= link_to "ORDER IN PROGRESS", order_delivery_path(order), :method => :post, :class=>"smsmessage btn btn-warning", remote: true, :style=>"margin-top:5px;margin-left:5px;", data: { toggle_text: 'DELIVERED', toggle_href: order_delivery_path ,id: order.id } %>
                <% elsif order.is_delivered == true %>
                <a class="btn btn-default">DELIVERED</a>
                  <%end%>

                  <%end%>
                </td>
               
               
                </tr>
                
                <% end %>
                
              </tbody>
            </table>

app/views/shared/_preorder_form.html.erb
<div id="1demo" class="collapse1">
<label for="fullname">Pre Order Delivery Time :</label>
<div class="col-md-12 col-sm-1 col-xs-12">
  <div class="" role="tabpanel" data-example-id="togglable-tabs">
    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
      <li role="presentation" class="active"><a  id="home-tab" role="tab"  aria-expanded="true" <% unless Date.today.to_time.strftime("%A") == "Tuesday"%> href="#tab_content1" data-toggle="tab">  AAJ<%else%> >Closed<%end%>  </a>
      </li>
      <li role="presentation" ><a class="disabled" role="tab" id="profile-tab"  aria-expanded="false" <% unless Date.tomorrow.to_time.strftime("%A") == "Tuesday"%> href="#tab_content2" data-toggle="tab">  KAL<%else%> >Closed<%end%></a>
      </li>
      <li role="presentation" class=""><a  role="tab" id="profile-tab2"  aria-expanded="false" <% unless Date.tomorrow.tomorrow.to_time.strftime("%A") == "Tuesday"%> href="#tab_content3" data-toggle="tab">PARSO<%else%> >Closed<%end%></a>
      </li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">10-11 AM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/10AM-11AM"%> <%="disabled" if current_hour > "08" %> />
            <div class="control__indicator" <% if current_hour > "08" %>
            style="background: #c9302c;" 
            <%end%> ></div>
          </label>
          <label class="control control--radio">1-2 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/01PM-02PM"%> <%="disabled" if current_hour > "11" %>/>
            <div class="control__indicator" <% if current_hour > "11" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">4-5 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/04PM-05PM"%> <%="disabled" if current_hour > "14" %>/>
            <div class="control__indicator" <% if current_hour > "14" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">7-8 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/07PM-08PM"%> <%="disabled" if current_hour > "17" %>/>
            <div class="control__indicator" <% if current_hour > "17" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
        </div>
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">11-12 AM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/11AM-12AM"%> <%="disabled" if current_hour > "09" %>/>
            <div class="control__indicator" <% if current_hour > "09" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">2-3 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/02PM-03PM"%> <%="disabled" if current_hour > "12" %>/>
            <div class="control__indicator" <% if current_hour > "12" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">5-6 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/05PM-06PM"%> <%="disabled" if current_hour > "15" %>/>
            <div class="control__indicator" <% if current_hour > "15" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">8-9 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/08PM-09PM"%> <%="disabled" if current_hour > "18" %>/>
            <div class="control__indicator" <% if current_hour > "18" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
        </div>
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">12-1 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/12AM-01PM"%> <%="disabled" if current_hour > "10" %>/>
            <div class="control__indicator" <% if current_hour > "10" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">3-4 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/03PM-04PM"%> <%="disabled" if current_hour > "13" %>/>
            <div class="control__indicator" <% if current_hour > "13" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">6-7 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/06PM-07PM"%> <%="disabled" if current_hour > "16" %>/>
            <div class="control__indicator" <% if current_hour > "16" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
          <label class="control control--radio">9-10 PM
            <input type="radio" name="delivery_time" value=<%="#{today_date}/09PM-10PM"%> <%="disabled" if current_hour > "19" %> />
            <div class="control__indicator" <% if current_hour > "19" %>
            style="background: #c9302c;" 
            <%end%>></div>
          </label>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">10-11 AM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/10AM-11AM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">1-2 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/01PM-02PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">4-5 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/04PM-05PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">7-8 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/07PM-08PM"%>/>
            <div class="control__indicator"></div>
          </label>
        </div>
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">11-12 AM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/11AM-12AM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">2-3 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/02PM-03PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">5-6 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/05PM-06PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">8-9 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/08PM-09PM"%>/>
            <div class="control__indicator"></div>
          </label>
        </div>
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">12-1 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/12AM-01PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">3-4 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/03PM-04PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">6-7 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/06PM-07PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">9-10 PM
            <input type="radio" name="delivery_time" value=<%="#{tommorow_date}/09PM-10PM"%>/>
            <div class="control__indicator"></div>
          </label>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">10-11 AM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/10AM-11AM"%> />
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">1-2 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/01PM-02PM"%> />
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">4-5 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/04PM-05PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">7-8 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/07PM-08PM"%>/>
            <div class="control__indicator"></div>
          </label>
        </div>
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">11-12 AM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/11AM-12AM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">2-3 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/02PM-03PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">5-6 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/05PM-06PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">8-9 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/08PM-09PM"%> />
            <div class="control__indicator"></div>
          </label>
        </div>
        <div class="col-md-4 col-sm-1 col-xs-4">
          <label class="control control--radio">12-1 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/12AM-01PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">3-4 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/03PM-04PM"%> />
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">6-7 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/06PM-07PM"%>/>
            <div class="control__indicator"></div>
          </label>
          <label class="control control--radio">9-10 PM
            <input type="radio" name="delivery_time" value=<%="#{day_after_tommorow}/09PM-10PM"%>/>
            <div class="control__indicator"></div>
          </label>
        </div>
      </div>
    </div>
  </div>
</div>
</div>