config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :recipes do
    collection do
      post :import
    end
  end
  resources :orders
  resources :recipes
  resources :merchants
  resources :customers
  resources :sms_messages
  resources :merchant_informations
  post 'add_wallet_money' => 'merchants#add_wallet_money'
  get 'cart'=> 'pages#cart'

  put 'add_to_cart' => 'recipes#add_to_cart'

  delete 'remove_cart_item' => 'recipes#remove_cart_item'
  delete 'delete_merchant' => 'merchants#destroy'

  post 'auto_complete' => 'orders#autocomplete'

  post 'new_new_order' => 'orders#new'
  get 'new_new_order' => 'customers#new'
  get 'my_orders' => 'pages#my_orders'

  post 'availability' => "recipes#availability"
  post 'shop_open' => "pages#shop_open"
  post 'cusine' => "pages#home"

  get 'closed_shop' => "pages#closed_shop"

  post 'sms_accept' => "pages#sms_accept"

  post 'send_sms' => "pages#send_sms"

  post 'accept_sms' => "pages#accept_sms"

  post 'reject_sms' => "pages#reject_sms"

  post 'order_delivery' => "orders#order_delivery"
  
  patch 'update_discount' => "pages#update_discount"
  patch 'update_pin' => "pages#update_pin"

  patch 'recipes' => "recipes#index"
  patch 'orders' => "orders#index"
  patch 'merchants' => "merchants#index"
  post 'set_sms' => "sms_messages#set_sms"
  post 'accept_merchant_information' => "merchant_informations#accept_merchant_information"
  devise_for :users, controllers: { sessions: 'users/sessions' ,:registrations => "users/registrations" }

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :recipes, through: :order_recipes
  has_many :order_recipes
  belongs_to :customer
  belongs_to :customer_address
  belongs_to :user
  has_many :notes_orders
  validates :amount, presence: true
  validates :o_id, presence: true, uniqueness: true
	
	end

app/controllers/orders_controller.rb
require "http"
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin? || :manager? || :operator?, only: [:destroy, :index]
  before_action :shop_opened , only: [:new]


  # GET /orders
  # GET /orders.json
  def index
  
    @orders = Order.all.sort_by(&:created_at).reverse
    @stat = Stat.first
    @shop_open = Stat.first.shop_open
    @stat_second = Stat.new
    
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    @order_recipes = @order.recipes
    @stat = Stat.first

  end

  # GET /orders/new
  def new
   @cart_recipes = current_user.recipes
    if @cart_recipes.empty?
      redirect_to root_path, notice: 'Please Add Recipe Kit In Cart'
    else
    @customer_address = CustomerAddress.new
    @order = Order.new
    @notes_order = NotesOrder.new
    @customer = Customer.find_by_phone(params[:customer][:phone])
    if @customer
      @addresses = @customer.customer_addresses 
    else
      @customer = Customer.new
    end  
    @stat = Stat.first
   end
    
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
   @stat_message = Stat.first.pin.gsub ' ', '+'
    if params[:order][:customer_address][:address].present? && params[:order][:customer][:name].present? && params[:mode_of_payment].present?
      @stat = Stat.first
      @order = Order.new(order_params)

      @customer = Customer.find_by_phone(params[:order][:customer][:phone])
      if @customer
        @customer_address = CustomerAddress.find_by_address(params[:order][:customer_address][:address])
        if @customer_address
          @order.customer_address_id = @customer_address.id
        else
          @customer_address = CustomerAddress.new
          @customer_address.address = params[:order][:customer_address][:address]
          @customer_address.customer_id = @customer.id
          @customer_address.save
          @order.customer_address_id = @customer_address.id
        end 

        @order.user_id = current_user.id
        @order.customer_id = @customer.id

        @cart_recipes = current_user.recipes
        
        @cart_recipes.each do |recipe|
          @order.order_recipes.build(:recipe_id => recipe.id)
        end
        @current_user.cart_recipes.destroy_all
        if params[:n1].present?
          @order.notes_orders.build(:description => params[:n1]) 
        end
        if params[:n2].present?
          @order.notes_orders.build(:description => params[:n2]) 
        end
        if params[:n3].present?
          @order.notes_orders.build(:description => params[:n3]) 
        end
        if params[:n4].present?
          @order.notes_orders.build(:description => params[:n4]) 
        end
        @order.mode_of_payment = params[:mode_of_payment]
        if params[:delivery_time].present?
          @order.delivery_time = params[:delivery_time]
           
          
          unless params[:delivery_time].split("/")[0] == (Time.now).strftime('%d%m%Y')
            @order.amount = @cart_recipes.map(&:price).inject(0, :+)*(100 - @stat.discount.to_f)/100 + 11
            @order.preorder = true
          else
            
            if params[:delivery_time].split("/")[1].split("-")[0].to_time > (Time.now + 2.hours)
            @order.amount = @cart_recipes.map(&:price).inject(0, :+)*(100 - @stat.discount.to_f)/100 + 11
            @order.preorder = true
            else
            @order.amount = @cart_recipes.map(&:price).inject(0, :+) + 11
            end  
          end  
        else
          @order.amount = @cart_recipes.map(&:price).inject(0, :+) + 11
          if Time.current.to_s.split(" ")[1].split(":")[0] > "19"
             @order.delivery_time = "#{(Time.current + 1.day).strftime('%d%m%Y')}/10AM-11AM"
          else

          @order.delivery_time = "#{(Time.current).strftime('%d%m%Y')}/#{(Time.current + 2.hours).strftime("%I%p")}-#{(Time.current + 3.hours).strftime("%I%p")}"  
          end
        end
        @order.o_id = "#{current_user.merchant_pin}#{(Time.now).strftime('%d%m%Y')}#{current_user.orders.where("created_at >= ?", Time.zone.now.beginning_of_day).count}"
        
        respond_to do |format|
          if @order.save
            
           @order_recipes = @order.order_recipes
            @message = "Your+Order+"
            @order_recipes.each do |order_recipe|
              @message = @message +"," + "#{order_recipe.recipe.serving}" + "#{order_recipe.recipe.name}"
            end
           
           @message = @message.gsub ' ', '+'

            if @stat.sms_accept
            
               HTTP.get("http://sms.bulksms.net.in/api/pushsms.php?username=RISHII&password=5413&sender=GRFOOD&message=#{@message}+Total+Rs+#{@order.amount}+Delivered+by+#{@order.delivery_time}+is+confirmed+#{@stat_message}&numbers=#{@customer.phone}&unicode=false&flash=true")
              @order.sms_status = "Accepted"
              @order.save
            else
             
              HTTP.get("http://sms.bulksms.net.in/api/pushsms.php?username=RISHII&password=5413&sender=GRFOOD&message=#{@message}+Total+Rs+#{@order.amount}+Delivered+by+#{@order.delivery_time}+is+under+Review+#{@stat_message}&numbers=#{@customer.phone}&unicode=false&flash=true")
              end
            #  ExampleMailer.sample_email.deliver
            
            @wallet_user = current_user
            @wallet_user.wallet = @wallet_user.wallet - @order.amount
            @wallet_user.save
            format.html { redirect_to order_path(@order), notice: 'Order was successfull.' }
            format.json { render :show, status: :created, location: @order }
          else
            format.html { render :new }
            format.json { render json: @order.errors, status: :unprocessable_entity }
          end
        end 
      else 
        @customer = Customer.new
    
        @customer.phone = params[:order][:customer][:phone]
        @customer.name = params[:order][:customer][:name]
        @customer.save
       
        @customer_address = CustomerAddress.new
        @customer_address.address = params[:order][:customer_address][:address]
        @customer_address.customer_id = @customer.id
        @customer_address.save
        @order.customer_address_id = @customer_address.id

        @order.user_id = current_user.id
        @order.customer_id = @customer.id

        @cart_recipes = current_user.recipes
        
        @cart_recipes.each do |recipe|
          @order.order_recipes.build(:recipe_id => recipe.id)
        end
        @current_user.cart_recipes.destroy_all
  
        if params[:n1].present?
          @order.notes_orders.build(:description => params[:n1]) 
        end
        if params[:n2].present?
          @order.notes_orders.build(:description => params[:n2]) 
        end
        if params[:n3].present?
          @order.notes_orders.build(:description => params[:n3]) 
        end
        if params[:n4].present?
          @order.notes_orders.build(:description => params[:n4]) 
        end
        @order.mode_of_payment = params[:mode_of_payment]
        if params[:delivery_time].present?
          @order.delivery_time = params[:delivery_time]
          unless params[:delivery_time].split("/")[0] == (Time.now).strftime('%d%m%Y')
            @order.amount = @cart_recipes.map(&:price).inject(0, :+)*(100 - @stat.discount.to_f)/100 + 11
            @order.preorder = true
          else
            if params[:delivery_time].split("/")[1].split("-")[0].to_time > (Time.now + 2.hours)
            @order.amount = @cart_recipes.map(&:price).inject(0, :+)*(100 - @stat.discount.to_f)/100 + 11
            @order.preorder = true
            else
            @order.amount = @cart_recipes.map(&:price).inject(0, :+) + 11
            end  
          end  
        else
          @order.amount = @cart_recipes.map(&:price).inject(0, :+) + 11
         if Time.current.to_s.split(" ")[1].split(":")[0] > "19"
             @order.delivery_time = "#{(Time.current + 1.day).strftime('%d%m%Y')}/10AM-11AM"
          else
          @order.delivery_time = "#{(Time.current).strftime('%d%m%Y')}/#{(Time.current + 2.hours).strftime("%I%p")}-#{(Time.current + 3.hours).strftime("%I%p")}"  
          end
        end  
        @order.o_id = "#{current_user.merchant_pin}#{(Time.now).strftime('%d%m%Y')}#{current_user.orders.where("created_at >= ?", Time.zone.now.beginning_of_day).count}"
        respond_to do |format|
          if @order.save
            @order_recipes = @order.order_recipes
            @message = "Your+Order+"
            @order_recipes.each do |order_recipe|
              @message = @message +"," + "#{order_recipe.recipe.serving}" + "#{order_recipe.recipe.name}"
            end
           @message = @message.gsub ' ', '+'
           if @stat.sms_accept
              HTTP.get("http://sms.bulksms.net.in/api/pushsms.php?username=RISHII&password=5413&sender=GRFOOD&message=#{@message}+Total+Rs+#{@order.amount}+Delivered+by+#{@order.delivery_time}+is+confirmed+#{@stat_message}&numbers=#{@customer.phone}&unicode=false&flash=true")
              @order.sms_status = "Accepted"
              @order.save
            else
              HTTP.get("http://sms.bulksms.net.in/api/pushsms.php?username=RISHII&password=5413&sender=GRFOOD&message=#{@message}+Total+Rs+#{@order.amount}+Delivered+by+#{@order.delivery_time}+is+under+Review+#{@stat_message}&numbers=#{@customer.phone}&unicode=false&flash=true")
              end
              @wallet_user = current_user
            @wallet_user.wallet = @wallet_user.wallet - @order.amount
            @wallet_user.save
             # ExampleMailer.sample_email.deliver
               format.html { redirect_to order_path(@order), notice: 'Order was successfull.' }
            format.json { render :show, status: :created, location: @order }
          else
            format.html { render :new }

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="x_panel">
<center>
          
<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe , new_customer_path, data: { turbolinks: false },:class=> "pull-left"%>
  <h3>ORDER DETAILS</h3></center>
  <br>
  <div class="x_content">

<%= form_for(@order) do |f| %>
<form id="demo-form" data-parsley-validate>
<% if @customer.phone %>  
  <%= f.fields_for :customer do |l| %>
    <div class="field">
       <label for="fullname">Customer Phone No :</label>
      <%= l.text_field :phone, :value => @customer.phone, autofocus: true,:class=> "form-control",readonly: true%>   
    </div>
    <div class="field">
    <label for="fullname">Full Name :</label>
       
      <%= l.text_field :name, :value => @customer.name, autofocus: true,:class=> "form-control text-uppercase", :placeholder=>"ENTER CUSTOMER'S NAME" %>   
    </div>
  <% end %>

  <%= f.fields_for :customer_address do |l| %>
    <div class="field">
       <label for="fullname">Customer Address :</label>
      <%= l.text_area :address, autofocus: true,:value => @addresses.first.address, :id => "newaddress",:class=> "form-control" , :placeholder=>"ENTER CUSTOMER'S ADRESS"%>   
    </div>
    <div class="field">
    <label for="fullname">Select From Previous Addresses :</label>
      <%= l.select(:customer_address_id, @addresses.collect {|c| [c.address]},{},{  :class => "form-control",  :onchange=>"copyIt()"  , :id => "previousaddress", :value=>""})  %>
    </div>
  <% end %>

  
<% else %>
  <%= f.fields_for :customer do |l| %>
    <div class="field">
       <label for="fullname">Customer Phone No :</label>
      <%= l.text_field :phone, autofocus: true, :value => params[:customer][:phone],:class=> "form-control",readonly: true %>   
    </div>
    <div class="field">
       <label for="fullname">Full Name :</label>
      <%= l.text_field :name, autofocus: true,:class=> "form-control", :placeholder=>"ENTER CUSTOMER'S NAME" %>   
    </div>
  <% end %>

  <%= f.fields_for :customer_address do |l| %>
    <div class="field">
       <label for="fullname">Customer Address :</label>
      <%= l.text_area :address, autofocus: true,:class=> "form-control", :placeholder=>"ENTER CUSTOMER'S ADRESS" %>   
    </div>
  <% end %>
<% end %> 

<%= f.fields_for :notes_address do |l| %>
<label for="fullname">Additional Notes :</label>
    <div class="field">
      
      <div class="col-md-6 col-sm-3 col-xs-6">
        <label class="control control--radio">No Garlic
          <input type="checkbox" name="n1" value="No Garlic" />
          <div class="control__indicator"></div>
        </label>   
        <label class="control control--radio">No Onion 
          <input type="checkbox" name="n2" value="No Onion" />
          <div class="control__indicator"></div>
        </label> 
      </div>  
      <div class="col-md-6 col-sm-3 col-xs-6">
        <label class="control control--radio">No Bread
          <input type="checkbox" name="n3" value="No Bread" />
          <div class="control__indicator"></div>
        </label>   
        <label class="control control--radio">No Ginger 
          <input type="checkbox" name="n4" value="No Ginger" />
          <div class="control__indicator"></div>
        </label> 
      </div> 
    </div>
  <% end %>
   
  <label for="fullname">Mode of Payment :</label>
   
     
      <div class="field"> 
      <div class="col-md-6 col-sm-3 col-xs-6">
        <label class="control control--radio">Cash
          <input type="radio" name="mode_of_payment" value="Cash" />
          <div class="control__indicator"></div>
        </label>   
        
      </div>  
      <div class="col-md-6 col-sm-3 col-xs-6">
        <label class="control control--radio">Online
          <input type="radio" name="mode_of_payment" value="Online" />
          <div class="control__indicator"></div>
        </label>   
         
      </div> 
   
  </div>
  <a href="#demo" data-toggle="collapse" class="btn btn-info btn-block" style="margin-top: 45px;">AVAIL <%=@stat.discount %>% OFF ON PREORDER <i class="fa fa-arrow-down"></i></a>
  <br>
  <div id="demo" class="collapse">
<%= render 'shared/preorder_form'%>
</div>

    


  <div class="actions">
    <%= f.submit "PLACE ORDER" ,:class=> "btn btn-success btn-block btn-lg" , data: { turbolinks: false }%>
  </div>
  </form>
<% end %>


 </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>





<div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
     
          <div class="x_content">
            <h1 class="pull-left">Orders</h1>
          
                              <% if @shop_open %>
         
          <%= link_to "Close", shop_open_path, :method => :post, :class=>"addtocart btn btn-success", remote: true, :style=>"margin-top:15px;margin-left:20px;", data: { toggle_text: 'Open', toggle_href: shop_open_path ,id: current_user.id } %>
          <%else%>
          <%= link_to "Open", shop_open_path, :method => :post, :class=>"addtocart btn btn-danger", remote: true, :style=>"margin-top:15px;margin-left:20px;", data: { toggle_text: 'Close', toggle_href: shop_open_path , id: current_user.id }  %>
          <% end %>

          <% if @stat.sms_accept %>
         
          <%= link_to "Automatic Accept", sms_accept_path, :method => :post, :class=>"addtocart btn btn-success", remote: true, :style=>"margin-top:15px;margin-left:20px;", data: { toggle_text: 'Manual Accept', toggle_href: shop_open_path ,id: "sms#{current_user.id}" } %>
          <%else%>
          <%= link_to "Manual Accept", sms_accept_path, :method => :post, :class=>"addtocart btn btn-danger", remote: true, :style=>"margin-top:15px;margin-left:20px;", data: { toggle_text: 'Automatic Accept', toggle_href: sms_accept_path , id: "sms#{current_user.id}" }  %>
          <% end %>
        <% if admin %>
            <div class="pull-right form-inline">
            <%= form_for(@stat, url: update_discount_path) do |f| %>
            <!-- start form for validation -->
            <form id="demo-form" data-parsley-validate>
              <label for="fullname">Preorder Discount</label>
              <%= f.text_field :discount, autofocus: true ,:value => @stat.discount ,:class=> "form-control", data: { turbolinks: false }%>
            
             


            
             <%= f.submit "Update",:class=>"btn btn-success submit", :style=>"margin-top:5px" %>


                  

            </form>
            <% end %>
         
        
            </div>
            <%end%>

            <%= render 'shared/order' %>
          </div>
        </div>
      </div>

  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
     
          <div class="x_content">
          <center>
            <h3>ORDER NO. <%=@order.o_id%></h3></center>
            <table id="table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  
                  <th >RECIPE KIT ITEM</th>
                  <th>SERVINGS</th>
                  <th>RATE</th>
                  
                  
                </tr>
              </thead>


              <tbody>
              <% @order_recipes.each do |recipe| %>
                <tr>

                  <td class="text-uppercase"><%= recipe.name %></td>
                  <td ><span class="h4"><%= recipe.serving %> </span>Persons</td>
                  <td>RS.<span class="h4"><%= recipe.price %></span></td>
                  
               
                </tr>
                 <% end %>
               
                 <tr>
                 
                  
                  <td></td>
                   <td class="text-uppercase">Delivery Charges</td>
                  <td>Rs. <span class="h4">11</span></td>
               
                </tr>
                
              </tbody>
            </table>
             <% if @order.preorder %>
                <tr>
                   
                   <span class="h3">
                  </span>
                
                  <span class="h4"> Pre Order Discount : <%=@stat.discount %> %</span>
                  
                  
                  <div class="pull-right">
                   <span class="h4">Total Amount :
                    Rs<%=@order.recipes.map(&:price).inject(0, :+)%>
                    </span> 
                  </div>
                </tr>
               <%end%>
               <br>

             <tr>
                   <span class="h4">
                   
                  Total Items : 
                  </span>
                  <span class="h4"><%=@order_recipes.count%></span>
                  
                  <span class="pull-right">
                   <span class="h4">
                    Amount Paid : Rs.</span><span class="h3"><%=@order.amount%></span>
                  </span>
                </tr>

          </div>
          <%= link_to 'PAYMENT COLLECTED', root_path, :class=>"btn btn-success pull-right btn-block btn-lg", data: { turbolinks: false } %>
        </div>
      </div>
     
  </div>