config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :recipes do
    collection do
      post :import
    end
  end
  resources :orders
  resources :recipes
  resources :merchants
  resources :customers
  resources :sms_messages
  resources :merchant_informations
  post 'add_wallet_money' => 'merchants#add_wallet_money'
  get 'cart'=> 'pages#cart'

  put 'add_to_cart' => 'recipes#add_to_cart'

  delete 'remove_cart_item' => 'recipes#remove_cart_item'
  delete 'delete_merchant' => 'merchants#destroy'

  post 'auto_complete' => 'orders#autocomplete'

  post 'new_new_order' => 'orders#new'
  get 'new_new_order' => 'customers#new'
  get 'my_orders' => 'pages#my_orders'

  post 'availability' => "recipes#availability"
  post 'shop_open' => "pages#shop_open"
  post 'cusine' => "pages#home"

  get 'closed_shop' => "pages#closed_shop"

  post 'sms_accept' => "pages#sms_accept"

  post 'send_sms' => "pages#send_sms"

  post 'accept_sms' => "pages#accept_sms"

  post 'reject_sms' => "pages#reject_sms"

  post 'order_delivery' => "orders#order_delivery"
  
  patch 'update_discount' => "pages#update_discount"
  patch 'update_pin' => "pages#update_pin"

  patch 'recipes' => "recipes#index"
  patch 'orders' => "orders#index"
  patch 'merchants' => "merchants#index"
  post 'set_sms' => "sms_messages#set_sms"
  post 'accept_merchant_information' => "merchant_informations#accept_merchant_information"
  devise_for :users, controllers: { sessions: 'users/sessions' ,:registrations => "users/registrations" }

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin? || :marketing? , only: [ :destroy, :new]
  before_action :admin? , only: [ :add_wallet_moneyd]

  def index
	
    @users = User.all - User.where(:role => "admin")
    @user = User.new
  
	end

	def create
    @user = User.new(user_params)
   

    respond_to do |format|
      if @user.save
        format.html { redirect_to merchants_path, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        @users = User.all - User.where(:role => "admin")
        format.html { render :index }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to merchants_path, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:format])
    @user.destroy
  
      redirect_to merchants_path, notice: 'Merchant was successfully destroyed.' 
     
  end

  def add_wallet_money
    @user = User.find(params[:user_id])
    @user.wallet = @user.wallet + params[:user][:wallet].to_f
    @user.save
    redirect_to request.referer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:merchant_pin, :password, :password_confirmation, :full_name, :address, :phone, :non_veg, :role)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<div class="x_panel">
  <div class="x_content">
  <center>
<h1>Add Merchant</h1>
</center>
<%= form_for(@user, url: merchants_path) do |f| %>


  <div class="field">
    <%= f.label :Merchant_ID %><br />
    <%= f.text_field :merchant_pin,:value => "#{last_merchant_pin}", autofocus: true , :class=> "form-control"%>
  </div>

  <div class="field">
    <%= f.label :Merchant_PIN %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", :class=> "form-control" %>
  </div>

  <div class="field">
    <%= f.label :Merchant_PIN_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", :class=> "form-control" %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name, autofocus: true, :class=> "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, autofocus: true , :class=> "form-control"%>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone, autofocus: true , :class=> "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Veg_NonVeg %><br />
    <%= f.select :non_veg, options_for_select([['ALL','true'],['VEG','false']]),
      {}, :class=> "form-control"%>
  </div>
  <% if admin %>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, options_for_select([['MERCHANT','merchant'],['MANAGER','manager'],['OPERATOR','operator'],['DATA ENTRY','data_entry'],['MARKETING','marketing']]),
      {}, :class=> "form-control"%>
  </div>
  <% else %>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, options_for_select([['MERCHANT','merchant']]),
      {}, :class=> "form-control"%>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Create Merchant" ,:class=>"btn btn-success btn-block btn-lg", data: { turbolinks: false } %>
  </div>
<% end %>
</div>
</div>

app/views/merchants/index.html.erb
<%= render 'form' %>
<p id="notice"><%= notice %></p>




<div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
     
          <div class="x_content">
          <center>
            <h1>Merchants</h1></center>
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Merchant ID</th>
                  <th>Name</th>
                  <th>Role</th>
                  <th>Address</th>
                  <th>Phone</th>
                  <th>Wallet</th>
                  <% if admin %>
                   <th>Wallet</th>
                  <th>Action</th>
                  <% end %>
                  
                </tr>
              </thead>


              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td ><%= user.merchant_pin %></td>
                  <td class="text-uppercase"><%= user.full_name %></td>
                  <td class="text-uppercase"><%= user.role %></td>
                  <td class="text-uppercase"><%= user.address %></td>
                  <td><%= user.phone %></td>
                  <td><%= user.wallet %></td>
                  <% if admin %>
                  <td> <div class="form-inline">
            <%= form_for(@user, url: add_wallet_money_path) do |f| %>
            <!-- start form for validation -->
           <form id="demo-form" data-parsley-validate>
              <label for="fullname">Add Money</label>
              <%= hidden_field_tag 'user_id', user.id %>
              <%= f.text_field :wallet ,:class=> "form-control", data: { turbolinks: false }%>
            
             


            
             <%= f.submit "Update",:class=>"btn btn-success submit", :style=>"margin-top:5px" %>


                  

            </form>
             <% end %>
             </div>






            </td>
                  <td>
                  <%= link_to 'Edit', edit_merchant_path(user), :class=> "btn btn-primary", data: { turbolinks: false } %>
                  <%= link_to 'Destroy', delete_merchant_path(user), method: :delete, data: { confirm: 'Are you sure?' } ,:class=> "btn btn-danger"%>
                    
                  </td><% end %>
               
                </tr>
                <% end %>
                
              </tbody>
            </table>
          </div>
        </div>
      </div>

  </div>
</div>