config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :recipes do
    collection do
      post :import
    end
  end
  resources :orders
  resources :recipes
  resources :merchants
  resources :customers
  resources :sms_messages
  resources :merchant_informations
  post 'add_wallet_money' => 'merchants#add_wallet_money'
  get 'cart'=> 'pages#cart'

  put 'add_to_cart' => 'recipes#add_to_cart'

  delete 'remove_cart_item' => 'recipes#remove_cart_item'
  delete 'delete_merchant' => 'merchants#destroy'

  post 'auto_complete' => 'orders#autocomplete'

  post 'new_new_order' => 'orders#new'
  get 'new_new_order' => 'customers#new'
  get 'my_orders' => 'pages#my_orders'

  post 'availability' => "recipes#availability"
  post 'shop_open' => "pages#shop_open"
  post 'cusine' => "pages#home"

  get 'closed_shop' => "pages#closed_shop"

  post 'sms_accept' => "pages#sms_accept"

  post 'send_sms' => "pages#send_sms"

  post 'accept_sms' => "pages#accept_sms"

  post 'reject_sms' => "pages#reject_sms"

  post 'order_delivery' => "orders#order_delivery"
  
  patch 'update_discount' => "pages#update_discount"
  patch 'update_pin' => "pages#update_pin"

  patch 'recipes' => "recipes#index"
  patch 'orders' => "orders#index"
  patch 'merchants' => "merchants#index"
  post 'set_sms' => "sms_messages#set_sms"
  post 'accept_merchant_information' => "merchant_informations#accept_merchant_information"
  devise_for :users, controllers: { sessions: 'users/sessions' ,:registrations => "users/registrations" }

end

app/views/layouts/_header.html.erb
<div class="top_nav navbar-fixed-top" style="margin-left: 0px;">
  <div class="nav_menu">
    <nav>      
      <%= link_to root_path, :style=>"background-color:#ededed;", data: { turbolinks: false } do %>
      <img src="/images/GR-logo-new.png" width="50px" style="padding-top:5px;margin-left:5px;">
      <%end%>
      <ul class="nav navbar-nav navbar-right">
        <% unless merchant %>      
        <li>
          <%= link_to 'Log Out'.html_safe, destroy_user_session_path,
                :method => :delete ,:class=>"user-profile dropdown-toggle"%>
        </li>
        <% end %>
        <% if admin || marketing %>
        <li>
          <%= link_to 'SMS' , sms_messages_path , data: { turbolinks: false },:class=>"user-profile dropdown-toggle" %>
        </li>
        <% end %>
        <% if admin || manager %>
        <li>
          <%= link_to 'ORDERS' , orders_path , data: { turbolinks: false },:class=>"user-profile dropdown-toggle" %>
        </li>
        <% end %>
        <% if admin || manager || data_entry%>
        <li>
          <%= link_to 'RECIPES' , recipes_path , data: { turbolinks: false },:class=>"user-profile dropdown-toggle" %>
        </li>
        <% end %>
        <% if admin || marketing %>
        <li>
          <%= link_to 'MERCHANTS' , merchants_path , data: { turbolinks: false },:class=>"user-profile dropdown-toggle" %>
        </li>
        <% end %> 
        <% if admin %>
        <li>
          <%= link_to 'MERCHANTS APPLICATIONS' , merchant_informations_path , data: { turbolinks: false },:class=>"user-profile dropdown-toggle" %>
        </li>
        <% end %>     
      </ul>

      <% if merchant %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="javascript:;"  class="btn-danger user-profile dropdown-toggle text-uppercase active" data-toggle="dropdown" aria-expanded="true" style="padding-top: 22px;padding-bottom: 9px;">
                <span class="h5" style="color:white;margin-right:5px;" >
                 <%= current_user.full_name.first(4) %></span>
                  <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li >
          <a><b>
          Rs <span class="h1" ><%= current_user.wallet %></span> </b><img class="pull-right" src="/images/wallet.png" width="30" >
          </a>
        </li>
                      <li>
                <a><i class="fa fa-phone pull-right"></i> 0129-414-6687
                </a>
              </li>
              <li>
                <%= link_to 'My Orders' , my_orders_path, data: { turbolinks: false } %>
              </li>    
              <li>
              <%= link_to  destroy_user_session_path,
                  :method => :delete, data: { turbolinks: false } do %>
                  
              <i class="fa fa-sign-out pull-right"></i> Log Out
              <%end%>
              </li>
            </ul>
          </li>
          <li role="presentation" class="dropdown" >
            <%= link_to cart_path , :class=> "nohover btn-success dropdown-toggle info-number",:style=> "padding-bottom:9px;padding-top: 8px;" ,data: { turbolinks: false } do %><b>
            <span style="color:white;"> <span class="addtocart-count h1" data-id="<%= current_user.id %>"><%= current_user.cart_recipes.count %></span> ITEMS ADDED </b><i class="fa fa-shopping-cart"></i></span>
            <% end %>
          </li>
        </ul>
      <% end %>
    </nav>
  </div>
  <% if merchant %>
    <% if params[:action] == "home" && params[:controller] == "pages" %>
      <center>
        <div class="hidden-xs" style="margin-bottom:5px;background-color:#ededed;">
          <%= link_to "INDIAN", cusine_path("Indian"),method: :post, data: { turbolinks: false, disable_with: 'Wait ...' }, class: 'btn btn-success', :style=> "margin-top: 0px;margin-right: 10px;"%>
          <%= link_to "CHINESE", cusine_path("Chinese"),method: :post, data: { turbolinks: false,disable_with: 'Wait ...' }, class: 'btn btn-success', :style=> "margin-top: 0px;margin-right: 10px;"%>
         <%= link_to "ALL", cusine_path("All"),method: :post, data: { turbolinks: false, disable_with: 'Wait ...' }, class: 'btn btn-success', :style=> "margin-top: 0px;margin-right: 10px;"%>
          <%= link_to "CONTINENTAL", cusine_path("Continental"),method: :post, data: { turbolinks: false, disable_with: 'Wait ...' }, class: 'btn btn-success', :style=> "margin-top: 0px;
      margin-right: 10px;"%>
          <%= link_to "ITALIAN", cusine_path("Italian"),method: :post, data: { turbolinks: false,disable_with: 'Wait ...' }, class: 'btn btn-success', :style=> "margin-top: 0px;
      margin-right: 10px;"%>
        </div>
        <div class="visible-xs" style="margin-bottom:7px;background-color:#ededed;">
          <%= link_to "INDIAN", cusine_path("Indian"),method: :post, data: { turbolinks: false, disable_with: 'Wait ...' }, class: 'btn btn-success btn-sm', :style=> "margin-top: 0px;margin-right: 0px;padding-left:8px;padding-right:8px;"%>
          <%= link_to "CHINESE", cusine_path("Chinese"),method: :post, data: { turbolinks: false,disable_with: 'Wait ...' }, class: 'btn btn-success btn-sm', :style=> "margin-top: 0px;
      margin-right: 0px;"%>
      <%= link_to "ALL", cusine_path("All"),method: :post, data: { turbolinks: false, disable_with: 'Wait ...' }, class: 'btn btn-success btn-sm', :style=> "margin-top: 0px;margin-right: 0px;padding-left:8px;padding-right:8px;"%>
          <%= link_to "CONTINENTAL", cusine_path("Continental"),method: :post, data: { turbolinks: false, disable_with: 'Wait ...' }, class: 'btn btn-success btn-sm', :style=> "margin-top: 0px;
      margin-right: 0px;padding-left:8px;padding-right:8px;"%>
          <%= link_to "ITALIAN", cusine_path("Italian"),method: :post, data: { turbolinks: false,disable_with: 'Wait ...' }, class: 'btn btn-success btn-sm', :style=> "margin-top: 0px;
      margin-right: 0px;padding-left:8px;padding-right:8px;"%>
        </div>
      </center>
    <%end%>
  <%end%>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grmerchant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if user_signed_in? %>
 <% if manager || operator || admin %>
  <% if params[:action] == "home" && params[:controller] == "pages"%>
  <meta http-equiv="refresh" content="30" >
  <%end%>
  <%end%>
  <%end%>
  <%= favicon_link_tag '/images/GR-logo-new.png' %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

  <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <link href="/custom.css" rel="stylesheet">
    <!-- iCheck -->
  


    <!-- Custom Theme Style -->
    <link href="/build/css/custom.min.css" rel="stylesheet">


    <link href="../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  
    

<!-- Latest compiled and minified JavaScript -->


</head>
<body class="nav-md" style="background-color:#dedede;">
<div class="container body" style="margin-top:60px;">
  <div class="main_container">
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <%end%>
    <%= yield %>
  </div>
</div>


    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
   
    <!-- NProgress -->
   
    <!-- Chart.js -->
 





    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>


   

</body>
</html>